version: '3.4'

services:
  meetmethere-be:
    image: meetmethere-be
    network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - 5000:5000
