version: '3.4'

services:
  food-diary-be:
    image: food-diary-be
    network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - 5000:5000
    networks:
      - dev_net

networks:
  dev_net:
    external: true
