import {MigrationInterface, QueryRunner} from "typeorm";

export class AddMissingRelation1620773367074 implements MigrationInterface {
    name = 'AddMissingRelation1620773367074'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `user_food_record` ADD `userId` int NOT NULL");
        await queryRunner.query("ALTER TABLE `fooddata` CHANGE `Food` `Food` varchar(45) NULL");
        await queryRunner.query("ALTER TABLE `fooddata` CHANGE `MainGroup` `MainGroup` varchar(10) NULL");
        await queryRunner.query("ALTER TABLE `fooddata` CHANGE `Group` `Group` varchar(25) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Food Name` `Food Name` varchar(91) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Description` `Description` varchar(220) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Group` `Group` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Previous` `Previous` varchar(28) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Main data references` `Main data references` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Footnote` `Footnote` varchar(177) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Edible proportion` `Edible proportion` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Specific gravity` `Specific gravity` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Total solids` `Total solids` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Nitrogen conversion factor` `Nitrogen conversion factor` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Glycerol conversion factor` `Glycerol conversion factor` varchar(18) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `WATER` `WATER` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `TOTNIT` `TOTNIT` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `PROT` `PROT` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAT` `FAT` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `CHO` `CHO` varchar(18) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `KCALS` `KCALS` varchar(5) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `KJ` `KJ` varchar(6) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `STAR` `STAR` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `OLIGO` `OLIGO` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `TOTSUG` `TOTSUG` varchar(18) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `GLUC` `GLUC` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `GALACT` `GALACT` varchar(2) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FRUCT` `FRUCT` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `SUCR` `SUCR` varchar(18) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `MALT` `MALT` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `LACT` `LACT` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `ALCO` `ALCO` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `ENGFIB` `ENGFIB` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `AOACFIB` `AOACFIB` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `SATFAC` `SATFAC` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `SATFOD` `SATFOD` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `TOTn6PFAC` `TOTn6PFAC` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `TOTn6PFOD` `TOTn6PFOD` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `TOTn3PFAC` `TOTn3PFAC` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `TOTn3PFOD` `TOTn3PFOD` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `MONOFACc` `MONOFACc` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `MONOFODc` `MONOFODc` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `MONOFAC` `MONOFAC` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `MONOFOD` `MONOFOD` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `POLYFACc` `POLYFACc` varchar(5) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `POLYFODc` `POLYFODc` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `POLYFAC` `POLYFAC` varchar(5) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `POLYFOD` `POLYFOD` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `SATFACx6` `SATFACx6` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `SATFODx6` `SATFODx6` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `TOTBRFAC` `TOTBRFAC` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `TOTBRFOD` `TOTBRFOD` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FACTRANS` `FACTRANS` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FODTRANS` `FODTRANS` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `CHOL` `CHOL` varchar(5) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `SODIUM` `SODIUM` varchar(5) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `K` `K` varchar(5) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `CA` `CA` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `MG` `MG` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `P` `P` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FE` `FE` varchar(5) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `CU` `CU` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `ZN` `ZN` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `CL` `CL` varchar(5) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `MN` `MN` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `SE` `SE` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `I` `I` varchar(6) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `RET` `RET` varchar(5) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `CAREQU` `CAREQU` varchar(5) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `RETEQU` `RETEQU` varchar(18) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `VITD` `VITD` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `VITE` `VITE` varchar(5) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `VITK1` `VITK1` varchar(5) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `THIA` `THIA` varchar(6) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `RIBO` `RIBO` varchar(6) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `NIAC` `NIAC` varchar(5) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `TRYP60` `TRYP60` varchar(6) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `NIACEQU` `NIACEQU` varchar(19) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `VITB6` `VITB6` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `VITB12` `VITB12` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOLT` `FOLT` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `PANTO` `PANTO` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `BIOT` `BIOT` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `VITC` `VITC` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `ALTRET` `ALTRET` varchar(5) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `13CISRET` `13CISRET` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `DEHYRET` `DEHYRET` varchar(1) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `RETALD` `RETALD` varchar(2) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `ACAR` `ACAR` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `BCAR` `BCAR` varchar(5) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `CRYPT` `CRYPT` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `LUT` `LUT` varchar(5) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `LYCO` `LYCO` varchar(5) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `25OHD3` `25OHD3` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `VITD3` `VITD3` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `5METHF` `5METHF` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `ATOPH` `ATOPH` varchar(5) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `BTOPH` `BTOPH` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `DTOPH` `DTOPH` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `GTOPH` `GTOPH` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `ATOTR` `ATOTR` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `GTOTR` `GTOTR` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC40` `FAC40` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC60` `FAC60` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC80` `FAC80` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC100` `FAC100` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC110xb` `FAC110xb` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC120` `FAC120` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC120xb` `FAC120xb` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC130` `FAC130` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC130xb` `FAC130xb` varchar(2) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC140` `FAC140` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC140xb` `FAC140xb` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC150` `FAC150` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC150xb` `FAC150xb` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC160` `FAC160` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC160xb` `FAC160xb` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC170` `FAC170` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC170xb` `FAC170xb` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC180` `FAC180` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC180xb` `FAC180xb` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC190` `FAC190` varchar(10) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC200` `FAC200` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC200xb` `FAC200xb` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC220` `FAC220` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC220xb` `FAC220xb` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC240` `FAC240` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC240xb` `FAC240xb` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC250xb` `FAC250xb` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD40` `FOD40` varchar(6) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD60` `FOD60` varchar(6) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD80` `FOD80` varchar(6) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD100` `FOD100` varchar(6) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD110xb` `FOD110xb` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD120` `FOD120` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD120xb` `FOD120xb` varchar(6) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD130` `FOD130` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD130xb` `FOD130xb` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD140` `FOD140` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD140xb` `FOD140xb` varchar(6) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD150` `FOD150` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD150xb` `FOD150xb` varchar(6) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD160` `FOD160` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD160xb` `FOD160xb` varchar(6) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD170` `FOD170` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD170xb` `FOD170xb` varchar(6) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD180` `FOD180` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD180xb` `FOD180xb` varchar(6) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD190` `FOD190` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD200` `FOD200` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD200xb` `FOD200xb` varchar(6) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD220` `FOD220` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD220xb` `FOD220xb` varchar(6) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD240` `FOD240` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD240xb` `FOD240xb` varchar(6) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD250xb` `FOD250xb` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC101` `FAC101` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC101c` `FAC101c` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC121` `FAC121` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC121c` `FAC121c` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC141` `FAC141` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC141c` `FAC141c` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC151` `FAC151` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC151c` `FAC151c` varchar(6) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC161` `FAC161` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC161c` `FAC161c` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC171` `FAC171` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC171c` `FAC171c` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC181` `FAC181` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC181c` `FAC181c` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC181n9` `FAC181n9` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC181n7` `FAC181n7` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC201` `FAC201` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC201c` `FAC201c` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC221` `FAC221` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC221c` `FAC221c` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC221n11` `FAC221n11` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC221n9` `FAC221n9` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC241` `FAC241` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC241c` `FAC241c` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `MONOFACtr` `MONOFACtr` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD101` `FOD101` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD101c` `FOD101c` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD121` `FOD121` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD121c` `FOD121c` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD141` `FOD141` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD141c` `FOD141c` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD151` `FOD151` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD151c` `FOD151c` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD161` `FOD161` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD161c` `FOD161c` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD171` `FOD171` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD171c` `FOD171c` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD181` `FOD181` varchar(5) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD181c` `FOD181c` varchar(5) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD181n9` `FOD181n9` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD181n7` `FOD181n7` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD201` `FOD201` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD201c` `FOD201c` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD221` `FOD221` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD221c` `FOD221c` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD221n11` `FOD221n11` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD221n9` `FOD221n9` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD241` `FOD241` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD241c` `FOD241c` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `MONOFODtr` `MONOFODtr` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC162` `FAC162` varchar(10) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC162c` `FAC162c` varchar(10) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC163c` `FAC163c` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC164` `FAC164` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC164c` `FAC164c` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC16 poly` `FAC16 poly` varchar(10) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC182` `FAC182` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC182cn6` `FAC182cn6` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC183` `FAC183` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC183cn3` `FAC183cn3` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC183cn6` `FAC183cn6` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC184` `FAC184` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC184cn3` `FAC184cn3` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC18 poly` `FAC18 poly` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC202` `FAC202` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC202cn6` `FAC202cn6` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC203` `FAC203` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC203cn6` `FAC203cn6` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC204` `FAC204` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC204cn6` `FAC204cn6` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC205` `FAC205` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC205cn3` `FAC205cn3` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC20 poly` `FAC20 poly` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC215` `FAC215` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC215cn3` `FAC215cn3` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC222` `FAC222` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC222cn6` `FAC222cn6` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC223cn6` `FAC223cn6` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC224` `FAC224` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC224cn6` `FAC224cn6` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC225` `FAC225` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC225cn3` `FAC225cn3` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC226` `FAC226` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC226cn3` `FAC226cn3` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC22 poly` `FAC22 poly` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `POLYFACtr` `POLYFACtr` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD162` `FOD162` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD162c` `FOD162c` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD163` `FOD163` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD164` `FOD164` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD164c` `FOD164c` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD16 poly` `FOD16 poly` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD182` `FOD182` varchar(5) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD182cn6` `FOD182cn6` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD183` `FOD183` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD183cn3` `FOD183cn3` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD183cn6` `FOD183cn6` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD184` `FOD184` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD184cn3` `FOD184cn3` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD18 poly` `FOD18 poly` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD202` `FOD202` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD202cn6` `FOD202cn6` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD203` `FOD203` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD203cn6` `FOD203cn6` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD204` `FOD204` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD204cn6` `FOD204cn6` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD205` `FOD205` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD205cn3` `FOD205cn3` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD20 poly` `FOD20 poly` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD215` `FOD215` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD215cn3` `FOD215cn3` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD222` `FOD222` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD222cn6` `FOD222cn6` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD223cn6` `FOD223cn6` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD224` `FOD224` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD224cn6` `FOD224cn6` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD225` `FOD225` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD225cn3` `FOD225cn3` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD226` `FOD226` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD226cn3` `FOD226cn3` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD22 poly` `FOD22 poly` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `POLYFODtr` `POLYFODtr` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Total PHYTO` `Total PHYTO` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Other CHOL and PHYTO` `Other CHOL and PHYTO` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `PHYTO` `PHYTO` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `BSITPHYTO` `BSITPHYTO` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `BRASPHYTO` `BRASPHYTO` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `CAMPHYTO` `CAMPHYTO` varchar(4) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `D5AVEN` `D5AVEN` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `D7AVEN` `D7AVEN` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `D7STIG` `D7STIG` varchar(2) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `STIGPHYTO` `STIGPHYTO` varchar(3) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `CITA` `CITA` varchar(2) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `MALA` `MALA` varchar(2) NULL");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `TimeInserted` `TimeInserted` varchar(19) NULL");
        await queryRunner.query("ALTER TABLE `token` CHANGE `deleteDate` `deleteDate` datetime(6) NULL");
        await queryRunner.query("ALTER TABLE `user` CHANGE `deleteDate` `deleteDate` datetime(6) NULL");
        await queryRunner.query("ALTER TABLE `user_food_record_entry` DROP FOREIGN KEY `FK_0565805c74df9aa89abde7eeaed`");
        await queryRunner.query("ALTER TABLE `user_food_record_entry` DROP FOREIGN KEY `FK_d732df2b624b7e117689ff15aa0`");
        await queryRunner.query("ALTER TABLE `user_food_record_entry` CHANGE `deleteDate` `deleteDate` datetime(6) NULL");
        await queryRunner.query("ALTER TABLE `user_food_record_entry` CHANGE `foodDataId` `foodDataId` int NOT NULL");
        await queryRunner.query("ALTER TABLE `user_food_record_entry` CHANGE `userFoodRecordId` `userFoodRecordId` int NULL");
        await queryRunner.query("ALTER TABLE `user_food_record` CHANGE `deleteDate` `deleteDate` datetime(6) NULL");
        await queryRunner.query("ALTER TABLE `user_food_record_entry` ADD CONSTRAINT `FK_d732df2b624b7e117689ff15aa0` FOREIGN KEY (`userFoodRecordId`) REFERENCES `user_food_record`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_food_record_entry` ADD CONSTRAINT `FK_0565805c74df9aa89abde7eeaed` FOREIGN KEY (`foodDataId`) REFERENCES `fooddata`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_food_record` ADD CONSTRAINT `FK_13b3e511b3c9bc8a2c4647ce1fc` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `user_food_record` DROP FOREIGN KEY `FK_13b3e511b3c9bc8a2c4647ce1fc`");
        await queryRunner.query("ALTER TABLE `user_food_record_entry` DROP FOREIGN KEY `FK_0565805c74df9aa89abde7eeaed`");
        await queryRunner.query("ALTER TABLE `user_food_record_entry` DROP FOREIGN KEY `FK_d732df2b624b7e117689ff15aa0`");
        await queryRunner.query("ALTER TABLE `user_food_record` CHANGE `deleteDate` `deleteDate` datetime(6) NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `user_food_record_entry` CHANGE `userFoodRecordId` `userFoodRecordId` int NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `user_food_record_entry` CHANGE `foodDataId` `foodDataId` int NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `user_food_record_entry` CHANGE `deleteDate` `deleteDate` datetime(6) NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `user_food_record_entry` ADD CONSTRAINT `FK_d732df2b624b7e117689ff15aa0` FOREIGN KEY (`userFoodRecordId`) REFERENCES `user_food_record`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_food_record_entry` ADD CONSTRAINT `FK_0565805c74df9aa89abde7eeaed` FOREIGN KEY (`foodDataId`) REFERENCES `fooddata`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user` CHANGE `deleteDate` `deleteDate` datetime(6) NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `token` CHANGE `deleteDate` `deleteDate` datetime(6) NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `TimeInserted` `TimeInserted` varchar(19) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `MALA` `MALA` varchar(2) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `CITA` `CITA` varchar(2) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `STIGPHYTO` `STIGPHYTO` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `D7STIG` `D7STIG` varchar(2) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `D7AVEN` `D7AVEN` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `D5AVEN` `D5AVEN` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `CAMPHYTO` `CAMPHYTO` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `BRASPHYTO` `BRASPHYTO` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `BSITPHYTO` `BSITPHYTO` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `PHYTO` `PHYTO` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Other CHOL and PHYTO` `Other CHOL and PHYTO` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Total PHYTO` `Total PHYTO` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `POLYFODtr` `POLYFODtr` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD22 poly` `FOD22 poly` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD226cn3` `FOD226cn3` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD226` `FOD226` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD225cn3` `FOD225cn3` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD225` `FOD225` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD224cn6` `FOD224cn6` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD224` `FOD224` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD223cn6` `FOD223cn6` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD222cn6` `FOD222cn6` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD222` `FOD222` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD215cn3` `FOD215cn3` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD215` `FOD215` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD20 poly` `FOD20 poly` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD205cn3` `FOD205cn3` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD205` `FOD205` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD204cn6` `FOD204cn6` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD204` `FOD204` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD203cn6` `FOD203cn6` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD203` `FOD203` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD202cn6` `FOD202cn6` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD202` `FOD202` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD18 poly` `FOD18 poly` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD184cn3` `FOD184cn3` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD184` `FOD184` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD183cn6` `FOD183cn6` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD183cn3` `FOD183cn3` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD183` `FOD183` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD182cn6` `FOD182cn6` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD182` `FOD182` varchar(5) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD16 poly` `FOD16 poly` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD164c` `FOD164c` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD164` `FOD164` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD163` `FOD163` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD162c` `FOD162c` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD162` `FOD162` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `POLYFACtr` `POLYFACtr` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC22 poly` `FAC22 poly` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC226cn3` `FAC226cn3` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC226` `FAC226` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC225cn3` `FAC225cn3` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC225` `FAC225` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC224cn6` `FAC224cn6` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC224` `FAC224` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC223cn6` `FAC223cn6` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC222cn6` `FAC222cn6` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC222` `FAC222` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC215cn3` `FAC215cn3` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC215` `FAC215` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC20 poly` `FAC20 poly` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC205cn3` `FAC205cn3` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC205` `FAC205` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC204cn6` `FAC204cn6` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC204` `FAC204` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC203cn6` `FAC203cn6` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC203` `FAC203` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC202cn6` `FAC202cn6` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC202` `FAC202` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC18 poly` `FAC18 poly` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC184cn3` `FAC184cn3` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC184` `FAC184` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC183cn6` `FAC183cn6` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC183cn3` `FAC183cn3` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC183` `FAC183` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC182cn6` `FAC182cn6` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC182` `FAC182` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC16 poly` `FAC16 poly` varchar(10) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC164c` `FAC164c` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC164` `FAC164` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC163c` `FAC163c` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC162c` `FAC162c` varchar(10) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC162` `FAC162` varchar(10) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `MONOFODtr` `MONOFODtr` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD241c` `FOD241c` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD241` `FOD241` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD221n9` `FOD221n9` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD221n11` `FOD221n11` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD221c` `FOD221c` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD221` `FOD221` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD201c` `FOD201c` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD201` `FOD201` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD181n7` `FOD181n7` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD181n9` `FOD181n9` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD181c` `FOD181c` varchar(5) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD181` `FOD181` varchar(5) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD171c` `FOD171c` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD171` `FOD171` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD161c` `FOD161c` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD161` `FOD161` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD151c` `FOD151c` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD151` `FOD151` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD141c` `FOD141c` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD141` `FOD141` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD121c` `FOD121c` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD121` `FOD121` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD101c` `FOD101c` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD101` `FOD101` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `MONOFACtr` `MONOFACtr` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC241c` `FAC241c` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC241` `FAC241` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC221n9` `FAC221n9` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC221n11` `FAC221n11` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC221c` `FAC221c` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC221` `FAC221` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC201c` `FAC201c` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC201` `FAC201` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC181n7` `FAC181n7` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC181n9` `FAC181n9` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC181c` `FAC181c` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC181` `FAC181` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC171c` `FAC171c` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC171` `FAC171` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC161c` `FAC161c` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC161` `FAC161` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC151c` `FAC151c` varchar(6) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC151` `FAC151` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC141c` `FAC141c` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC141` `FAC141` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC121c` `FAC121c` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC121` `FAC121` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC101c` `FAC101c` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC101` `FAC101` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD250xb` `FOD250xb` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD240xb` `FOD240xb` varchar(6) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD240` `FOD240` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD220xb` `FOD220xb` varchar(6) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD220` `FOD220` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD200xb` `FOD200xb` varchar(6) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD200` `FOD200` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD190` `FOD190` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD180xb` `FOD180xb` varchar(6) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD180` `FOD180` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD170xb` `FOD170xb` varchar(6) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD170` `FOD170` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD160xb` `FOD160xb` varchar(6) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD160` `FOD160` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD150xb` `FOD150xb` varchar(6) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD150` `FOD150` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD140xb` `FOD140xb` varchar(6) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD140` `FOD140` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD130xb` `FOD130xb` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD130` `FOD130` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD120xb` `FOD120xb` varchar(6) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD120` `FOD120` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD110xb` `FOD110xb` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD100` `FOD100` varchar(6) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD80` `FOD80` varchar(6) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD60` `FOD60` varchar(6) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOD40` `FOD40` varchar(6) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC250xb` `FAC250xb` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC240xb` `FAC240xb` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC240` `FAC240` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC220xb` `FAC220xb` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC220` `FAC220` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC200xb` `FAC200xb` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC200` `FAC200` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC190` `FAC190` varchar(10) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC180xb` `FAC180xb` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC180` `FAC180` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC170xb` `FAC170xb` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC170` `FAC170` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC160xb` `FAC160xb` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC160` `FAC160` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC150xb` `FAC150xb` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC150` `FAC150` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC140xb` `FAC140xb` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC140` `FAC140` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC130xb` `FAC130xb` varchar(2) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC130` `FAC130` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC120xb` `FAC120xb` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC120` `FAC120` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC110xb` `FAC110xb` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC100` `FAC100` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC80` `FAC80` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC60` `FAC60` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAC40` `FAC40` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `GTOTR` `GTOTR` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `ATOTR` `ATOTR` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `GTOPH` `GTOPH` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `DTOPH` `DTOPH` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `BTOPH` `BTOPH` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `ATOPH` `ATOPH` varchar(5) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `5METHF` `5METHF` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `VITD3` `VITD3` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `25OHD3` `25OHD3` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `LYCO` `LYCO` varchar(5) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `LUT` `LUT` varchar(5) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `CRYPT` `CRYPT` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `BCAR` `BCAR` varchar(5) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `ACAR` `ACAR` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `RETALD` `RETALD` varchar(2) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `DEHYRET` `DEHYRET` varchar(1) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `13CISRET` `13CISRET` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `ALTRET` `ALTRET` varchar(5) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `VITC` `VITC` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `BIOT` `BIOT` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `PANTO` `PANTO` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FOLT` `FOLT` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `VITB12` `VITB12` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `VITB6` `VITB6` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `NIACEQU` `NIACEQU` varchar(19) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `TRYP60` `TRYP60` varchar(6) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `NIAC` `NIAC` varchar(5) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `RIBO` `RIBO` varchar(6) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `THIA` `THIA` varchar(6) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `VITK1` `VITK1` varchar(5) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `VITE` `VITE` varchar(5) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `VITD` `VITD` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `RETEQU` `RETEQU` varchar(18) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `CAREQU` `CAREQU` varchar(5) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `RET` `RET` varchar(5) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `I` `I` varchar(6) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `SE` `SE` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `MN` `MN` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `CL` `CL` varchar(5) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `ZN` `ZN` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `CU` `CU` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FE` `FE` varchar(5) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `P` `P` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `MG` `MG` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `CA` `CA` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `K` `K` varchar(5) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `SODIUM` `SODIUM` varchar(5) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `CHOL` `CHOL` varchar(5) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FODTRANS` `FODTRANS` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FACTRANS` `FACTRANS` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `TOTBRFOD` `TOTBRFOD` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `TOTBRFAC` `TOTBRFAC` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `SATFODx6` `SATFODx6` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `SATFACx6` `SATFACx6` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `POLYFOD` `POLYFOD` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `POLYFAC` `POLYFAC` varchar(5) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `POLYFODc` `POLYFODc` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `POLYFACc` `POLYFACc` varchar(5) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `MONOFOD` `MONOFOD` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `MONOFAC` `MONOFAC` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `MONOFODc` `MONOFODc` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `MONOFACc` `MONOFACc` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `TOTn3PFOD` `TOTn3PFOD` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `TOTn3PFAC` `TOTn3PFAC` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `TOTn6PFOD` `TOTn6PFOD` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `TOTn6PFAC` `TOTn6PFAC` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `SATFOD` `SATFOD` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `SATFAC` `SATFAC` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `AOACFIB` `AOACFIB` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `ENGFIB` `ENGFIB` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `ALCO` `ALCO` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `LACT` `LACT` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `MALT` `MALT` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `SUCR` `SUCR` varchar(18) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FRUCT` `FRUCT` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `GALACT` `GALACT` varchar(2) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `GLUC` `GLUC` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `TOTSUG` `TOTSUG` varchar(18) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `OLIGO` `OLIGO` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `STAR` `STAR` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `KJ` `KJ` varchar(6) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `KCALS` `KCALS` varchar(5) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `CHO` `CHO` varchar(18) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `FAT` `FAT` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `PROT` `PROT` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `TOTNIT` `TOTNIT` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `WATER` `WATER` varchar(4) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Glycerol conversion factor` `Glycerol conversion factor` varchar(18) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Nitrogen conversion factor` `Nitrogen conversion factor` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Total solids` `Total solids` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Specific gravity` `Specific gravity` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Edible proportion` `Edible proportion` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Footnote` `Footnote` varchar(177) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Main data references` `Main data references` varchar(255) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Previous` `Previous` varchar(28) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Group` `Group` varchar(3) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Description` `Description` varchar(220) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddatacomposition` CHANGE `Food Name` `Food Name` varchar(91) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddata` CHANGE `Group` `Group` varchar(25) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddata` CHANGE `MainGroup` `MainGroup` varchar(10) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `fooddata` CHANGE `Food` `Food` varchar(45) CHARACTER SET \"utf8\" COLLATE \"utf8_general_ci\" NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `user_food_record` DROP COLUMN `userId`");
    }

}
